<a href="https://colab.research.google.com/github/19K41A0503/Machine-learning-lab/blob/main/Revised_SVM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
irisdata = pd.read_csv('/content/drive/MyDrive/Machine Learning/iris (3).csv')
print(irisdata.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
X = irisdata.drop('Species', axis=1)
y = irisdata['Species']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [10]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [11]:
y_pred = svclassifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[8 0 0]
 [5 9 0]
 [0 0 8]]
                 precision    recall  f1-score   support

    Iris-setosa       0.62      1.00      0.76         8
Iris-versicolor       1.00      0.64      0.78        14
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           0.83        30
      macro avg       0.87      0.88      0.85        30
   weighted avg       0.90      0.83      0.84        30

