In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
irisdata = pd.read_csv('Iris.csv')
print(irisdata.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [3]:
X = irisdata.drop('Species', axis=1)
y = irisdata['Species']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [6]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [7]:
y_pred = svclassifier.predict(X_test)

In [8]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 2  4  0]
 [ 0  0 12]]
                 precision    recall  f1-score   support

    Iris-setosa       0.86      1.00      0.92        12
Iris-versicolor       1.00      0.67      0.80         6
 Iris-virginica       1.00      1.00      1.00        12

       accuracy                           0.93        30
      macro avg       0.95      0.89      0.91        30
   weighted avg       0.94      0.93      0.93        30

